In [ ]:
#Union of 2 sets

set1 = {1,2,3,4}
set2 = {5,6}
set34 = set1|set2
print(set34)


{1, 2, 3, 4, 5, 6}


In [ ]:
#Intersection of 2 sets

set1 = {1,2,3,4}
set2 = {2,4}
set3 = set1 and set2
print(set3)

{2, 4}


In [ ]:
#Difference of 2 sets

set1 = {1,2,3,4}
set2 = {2,4}
set3 = set1-set2
print(set3)

{1, 3}


In [ ]:
#Symmetric operation

set1 = {1,2,3,4}
set2 = {1,3,5,6}
set3 = set1 ^ set2
print(set3)

{2, 4, 5, 6}


In [ ]:
#Equal

set1 = {1,2,3,4}
set2 = {1,2,3,4}
set3 = set1 == set2
print(set3)

True


In [ ]:
import numpy as np
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
import numpy as np
a = np.array([[1,2,3,4],
      [1,2,3,4]])
print(a)
print(a.shape)

[[1 2 3 4]
 [1 2 3 4]]
(2, 4)


In [ ]:
#array with evenly spaced value
import numpy as np
a = np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [ ]:
#array with linear space value
import numpy as np
a = np.linspace(1,10,5)
print(a)

[ 1.    3.25  5.5   7.75 10.  ]


In [ ]:
#array with identity matrix
import numpy as np
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#random array
import numpy as np
a = np.random.rand(3)
print(a)

[0.94001257 0.00379378 0.7771724 ]


In [ ]:
#element wise addition
import numpy as np
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
c = np.add(a,b)
print(c)

[2 4 6 8]


In [ ]:
#element wise multiplication
import numpy as np
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
c = np.multiply(a,b)
print(c)

[ 1  4  9 16]


In [ ]:
#exponentiation
import numpy as np
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
c = np.exp(a)
print(c)

[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [ ]:
#square root
import numpy as np
a = np.array([1,2,3,4])
c = np.sqrt(a)
print(c)

[1.         1.41421356 1.73205081 2.        ]


In [ ]:
#mean
import numpy as np
a = np.array([1,2,3,4])
c = np.mean(a)
print(c)

2.5


In [ ]:
#median
import numpy as np
a = np.array([1,2,3,4])
c = np.median(a)
print(c)

2.5


In [ ]:
#standard deviation
import numpy as np
a = np.array([1,2,3,4])
c = np.std(a)
print(c)

1.118033988749895


In [ ]:
#minimum and maximum
import numpy as np
a = np.array([1,2,3,4])
print(a.min())
print(a.max())

1
4


In [ ]:
# 2d matrix multiplication
import numpy as np
a = np.array([[1,2],
      [3,4]])
b = np.array([[3,4],
      [1,2]])
c = np.matmul(a,b)
print(c)

[[ 5  8]
 [13 20]]


In [ ]:
# matrix inverse
import numpy as np
a = np.array([[1,2],
      [3,4]])
inv = np.linalg.inv(a)
print(inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
#random float in [0.0, 1.0]
import numpy as np
rand_float = np.random.random()
print(rand_float)

0.8527201399701548


In [ ]:
#random integer between 0 to 9
import numpy as np
rand_int = np.random.randint(0,10)
print(rand_int)

6
