In [1]:
print("Hello World")

Hello World


In [3]:
name = "Aritra"
age = 20
height = 5.11
student = True
print(type(name), type(age), type(height), type(student))

<class 'str'> <class 'int'> <class 'float'> <class 'bool'>


In [5]:
a = int(input("Enter 1st number: "))
b = int(input("Enter 2nd number: "))
add = a+b
sub = a-b
mul = a*b
div = a/b
mod = a%b
print("Addition: ",add)
print("Subtraction: ",sub)
print("Multiplication: ",mul)
print("Divison: ",div)
print("Modulo: ",mod)

Addition:  6
Subtraction:  2
Multiplication:  8
Divison:  2.0
Modulo:  0


In [8]:
n = int(input("Enter a number: "))
if (n<0):
    print("Negative")
elif (n>0):
    print("Positive")
else:
    print("Zero")

Zero


In [10]:
n = int(input("Enter a number: "))
if (n%2==0):
    print("Even")
else:
    print("Odd")

Odd


In [13]:
year = int(input("Enter year: "))
if (year%4==0 and year%100==0 or year%400==0):
    print("Leap year")
else:
    print("Leap year")

Leap year


In [17]:
n = int(input("Enter a number: "))
f=1
for i in range (1,n+1):
    f = f*i
print(f"Factorial of {n} is {f}")

Factorial of 5 is 120


In [19]:
n = int(input("Enter range number: "))
a = 0
b = 1
print(a)
print(b)
for i in range(2,n):
    c = a+b
    print(c)
    a = b
    b = c


0
1
1
2
3
5
8
13
21
34


In [20]:
def max(a,b):
    if (a>b):
        print(f"{a} greater than {b}")
    elif (a<b):
        print(f"{b} greater than {a}")
    else:
        print(f"{a} and {b} are both equal")

a = int(input("Enter 1st number: "))
b = int(input("Enter 2nd number: "))
max(a,b)
    

5 greater than 2


In [ ]:
l = [34,67,10,98,5]
l.reverse()
print(l)

[5, 98, 10, 67, 34]


In [22]:
import numpy as np
a = np.array([34,67,10,98,5])
print("Maximum: ",a.max())
print("Minimum: ",a.min())

Maximum:  98
Minimum:  5


In [28]:
def sum(l):
    tot = 0
    for i in l:
        tot = tot+i
    return tot

n = int(input("Enter the range: "))
print(f"Enter {n} elements")
l = []
for i in range(n):
    l.append(int(input()))
print("The list: ")
print(l)
print("The sum: ",sum(l))

Enter 5 elements
The list: 
[1, 2, 3, 4, 5]
The sum:  15


In [29]:
l = [34,67,10,98,5]
l.sort()
print(l)

[5, 10, 34, 67, 98]


In [30]:
s = {34,67,10,98,5}
print(s)

{34, 67, 98, 5, 10}


In [31]:
s1 = {1,2,3,4}
s2 = {5,6,7,8}
s = s1|s2
print(s)

{1, 2, 3, 4, 5, 6, 7, 8}


In [33]:
s1 = {1,5,7,4}
s2 = {5,6,7,8}
s = s1 & s2
print(s)

{5, 7}


In [34]:
s1 = {1,5,7,4}
s2 = {1,5,7,4}
check = s1==s2
print(check)

True


In [35]:
s1 = {1,5,7,4}
s2 = {5,6,7,8}
s = s1-s2
print(s)

{1, 4}


In [36]:
import numpy as np
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [37]:
a = np.array([[1,2,3,4],
             [5,6,7,8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [41]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [45]:
a = np.random.rand(3)
print(a)

[0.17865616 0.1793464  0.22381806]


In [46]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
c = np.multiply(a,b)
print(c)

[ 1  4  9 16]


In [47]:
a = np.array([1,2,3,4])
b = np.sqrt(a)
print(b)

[1.         1.41421356 1.73205081 2.        ]


In [48]:
a = np.array([1,2,3,4])
m = np.mean(a)
print(m)

2.5


In [51]:
a = np.array([1,2,3,4])
med = np.median(a)
print(med)

2.5


In [50]:
a = np.array([1,2,3,4])
sd = np.std(a)
print(sd)

1.118033988749895


In [60]:
a = np.array([[1,2],
              [3,4]])
a = np.array([[1,2],
              [3,4]])
c = np.matmul(a,b)
print(c)

[[11 14 17 20]
 [23 30 37 44]]


In [61]:
n = int(input("Enter range: "))
temp = []
for i in range(n):
    temp.append(int(input()))

a = np.array(temp)
print(a)

[1 2 3 4 5]


In [65]:
a = np.random.random()
print(a)

b = np.random.randint(0,10)
print(b)

0.6439672521219078
9
